calib:
  data: "pileval"
  num_samples: 128
  seq_length: 2048
  min_length: 2048
  max_length: 0
  seed: 42

quant:
  weight:
    args:
      bits: 4
      strategy: "group"
      group_shapes: [[1, 128]]
      symmetric: true
      observer: "memoryless-minmax"
    mod:
      method: "rtn"

eval:
  ppl:
    datasets:
      - wikitext
    num_samples: 128
    seq_length: 2048
  compare_baseline: true
  output_path: "output/qoq/results.json"