calib:
  data: "pileval"
  num_samples: 128
  seq_length: 512
  min_length: 0
  max_length: 0
  seed: 42

transform:
  path: ""
  smooth:
    enabled: true
    smooth_attn: true
    smooth_qkv: true
    smooth_vo: false
    smooth_ffn: true
    smooth_down: false
    proj_alpha: 0.85
    proj_beta: 0.15
    attn_alpha: 0.5
    attn_beta: 0

quant:
  weight:
    args:
      bits: 8
      strategy: "channel"
      symmetric: true
      observer: "memoryless-minmax"
    mod:
      method: "gptq"
      block_size: 128
      perc_damp: 0.01

  input:
    args:
      bits: 8
      symmetric: true
      strategy: "token"
      dynamic: true
      observer: "minmax"

eval:
  ppl:
    datasets:
      - wikitext
    num_samples: 128
    seq_length: 2048
  compare_baseline: true
  output_path: "output/qoq/results.json"